version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suscripciones
    ports:
      - "3000:3000"
    command: gulp
    environment:
      - NODE_ENV=development
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./sass:/usr/src/app/sass
      - ./css:/usr/src/app/css
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - app_network
      
  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge      

volumes:
  mysql-data:
